server:
  port: 8989
spring:
  profiles:
    active: dev
  jackson:
    locale: zh_CN
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 127.0.0.1
    port: 6379
  devtools:
    livereload:
      enabled: true
mybatis:
  mapper-locations: classpath:com/kit/springboot/web/mapper/**/*.xml
#  mapper-locations: classpath:mapper/**/*Mapper.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  page-size-zero: true
  support-methods-arguments: true
logging:
  level:
    root: info
    com.akm.springboot: debug
  path: C:\workspace\java\springboot\logs
---
#debug: true
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/akm-springboot?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
